 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ULtrasonic.c
 *
 * Description: source file for the ULtrasonic driver
 *
 * Author: Mohamed Elfeki
 *
 *******************************************************************************/

#include"Ultrasonic.h"
#include"icu.h"
#include"gpio.h"
#include"std_types.h"
#include<util/delay.h>
#include<avr/io.h>

Icu_ConfigType config={F_CPU_8,RISING};/*configure ICU to use F/8 and detect rising edge*/

uint8 g_edgeCount = 0;//variable to count number of edges falling or rising
uint32 g_timeHigh = 0;//variable to count the time for which the echo is high

void Ultrasonic_edgeProcessing(void)
{
	/* Description
	 This is the call back function called by the ICU driver.
	 This is used to calculate the high time (pulse time) generated by
	the ultrasonic sensor.*/

	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* +Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		Icu_DeInit(); /* Disable ICU Driver */
		g_edgeCount = 0;
		Icu_setEdgeDetectionType(RISING);
	}

}

void Ultrasonic_init(void)
{
	/*Description

	  Initialize the ICU driver as required.
	  Setup the ICU call back function.
	  Setup the direction for the trigger pin as output pin through the
	  GPIO driver*/
	Icu_init(&config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID , ULTRASONIC_TRIGGER_PIN_ID , PIN_OUTPUT);
}

void Ultrasonic_Trigger(void)
{
	/*Description

	  Send the Trigger pulse to the ULtrasonic.
	 */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID , ULTRASONIC_TRIGGER_PIN_ID , LOGIC_HIGH);//enable Trigger pin
	_delay_us(10);//wait 10 us
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID , ULTRASONIC_TRIGGER_PIN_ID , LOGIC_LOW);//disable Trigger pin
}

uint16 Ultrasonic_readDistance(void)
{
	/* Description
	   Send the trigger pulse by using Ultrasonic_Trigger function.
	   Start the measurements by the ICU from this moment.
	*/

	uint16 distance=0 ;
	Ultrasonic_Trigger();

	distance = (g_timeHigh/58.8) ;
	return distance;
}
